### ISSUE TITLE
compile to linux ? 

### ISSUE THREAD

**Issue by red0bear** [cannabiscoindev/cannabiscoin420#15]
I need know how tyo compile your cannabis on linux .....

In file included from main.h:8:0,
                 from checkpoints.cpp:10:
bignum.h:51:24: error: invalid use of incomplete type ‘BIGNUM {aka struct bignum_st}’
 class CBigNum : public BIGNUM
                        ^~~~~~
In file included from /usr/include/openssl/bn.h:32:0,
                 from bignum.h:10,
                 from main.h:8,
                 from checkpoints.cpp:10:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of ‘BIGNUM {aka struct bignum_st}’
 typedef struct bignum_st BIGNUM;
                ^~~~~~~~~
In file included from main.h:8:0,
                 from checkpoints.cpp:10:
bignum.h: In constructor ‘CBigNum::CBigNum()’:
bignum.h:56:9: error: ‘BN_init’ was not declared in this scope
         BN_init(this);
         ^~~~~~~
bignum.h:56:9: note: suggested alternative: ‘BN_print’
         BN_init(this);
         ^~~~~~~
         BN_print
bignum.h: In copy constructor ‘CBigNum::CBigNum(const CBigNum&)’:
bignum.h:61:9: error: ‘BN_init’ was not declared in this scope
         BN_init(this);
         ^~~~~~~
bignum.h:61:9: note: suggested alternative: ‘BN_print’
         BN_init(this);
         ^~~~~~~
         BN_print
bignum.h:62:30: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘BIGNUM* BN_copy(BIGNUM*, const BIGNUM*)’
         if (!BN_copy(this, &b))
                              ^
bignum.h:64:31: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘void BN_clear_free(BIGNUM*)’
             BN_clear_free(this);
                               ^
bignum.h: In member function ‘CBigNum& CBigNum::operator=(const CBigNum&)’:
bignum.h:71:30: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘BIGNUM* BN_copy(BIGNUM*, const BIGNUM*)’
         if (!BN_copy(this, &b))
                              ^
bignum.h: In destructor ‘CBigNum::~CBigNum()’:
bignum.h:78:27: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘void BN_clear_free(BIGNUM*)’
         BN_clear_free(this);
                           ^
bignum.h: In constructor ‘CBigNum::CBigNum(signed char)’:
bignum.h:82:35: error: ‘BN_init’ was not declared in this scope
     CBigNum(signed char n)      { BN_init(this); if (n >= 0) setulong(n); else setint64(n); }
                                   ^~~~~~~
bignum.h:82:35: note: suggested alternative: ‘BN_print’
     CBigNum(signed char n)      { BN_init(this); if (n >= 0) setulong(n); else setint64(n); }
                                   ^~~~~~~
                                   BN_print
bignum.h: In constructor ‘CBigNum::CBigNum(short int)’:
bignum.h:83:35: error: ‘BN_init’ was not declared in this scope
     CBigNum(short n)            { BN_init(this); if (n >= 0) setulong(n); else setint64(n); }
                                   ^~~~~~~
bignum.h:83:35: note: suggested alternative: ‘BN_print’
     CBigNum(short n)            { BN_init(this); if (n >= 0) setulong(n); else setint64(n); }
                                   ^~~~~~~
                                   BN_print
bignum.h: In constructor ‘CBigNum::CBigNum(int)’:
bignum.h:84:35: error: ‘BN_init’ was not declared in this scope
     CBigNum(int n)              { BN_init(this); if (n >= 0) setulong(n); else setint64(n); }
                                   ^~~~~~~
bignum.h:84:35: note: suggested alternative: ‘BN_print’
     CBigNum(int n)              { BN_init(this); if (n >= 0) setulong(n); else setint64(n); }
                                   ^~~~~~~
                                   BN_print
bignum.h: In constructor ‘CBigNum::CBigNum(long int)’:
bignum.h:85:35: error: ‘BN_init’ was not declared in this scope
     CBigNum(long n)             { BN_init(this); if (n >= 0) setulong(n); else setint64(n); }
                                   ^~~~~~~
bignum.h:85:35: note: suggested alternative: ‘BN_print’
     CBigNum(long n)             { BN_init(this); if (n >= 0) setulong(n); else setint64(n); }
                                   ^~~~~~~
                                   BN_print
bignum.h: In constructor ‘CBigNum::CBigNum(int64)’:
bignum.h:86:35: error: ‘BN_init’ was not declared in this scope
     CBigNum(int64 n)            { BN_init(this); setint64(n); }
                                   ^~~~~~~
bignum.h:86:35: note: suggested alternative: ‘BN_print’
     CBigNum(int64 n)            { BN_init(this); setint64(n); }
                                   ^~~~~~~
                                   BN_print
bignum.h: In constructor ‘CBigNum::CBigNum(unsigned char)’:
bignum.h:87:35: error: ‘BN_init’ was not declared in this scope
     CBigNum(unsigned char n)    { BN_init(this); setulong(n); }
                                   ^~~~~~~
bignum.h:87:35: note: suggested alternative: ‘BN_print’
     CBigNum(unsigned char n)    { BN_init(this); setulong(n); }
                                   ^~~~~~~
                                   BN_print
bignum.h: In constructor ‘CBigNum::CBigNum(short unsigned int)’:
bignum.h:88:35: error: ‘BN_init’ was not declared in this scope
     CBigNum(unsigned short n)   { BN_init(this); setulong(n); }
                                   ^~~~~~~
bignum.h:88:35: note: suggested alternative: ‘BN_print’
     CBigNum(unsigned short n)   { BN_init(this); setulong(n); }
                                   ^~~~~~~
                                   BN_print
bignum.h: In constructor ‘CBigNum::CBigNum(unsigned int)’:
bignum.h:89:35: error: ‘BN_init’ was not declared in this scope
     CBigNum(unsigned int n)     { BN_init(this); setulong(n); }
                                   ^~~~~~~
bignum.h:89:35: note: suggested alternative: ‘BN_print’
     CBigNum(unsigned int n)     { BN_init(this); setulong(n); }
                                   ^~~~~~~
                                   BN_print
bignum.h: In constructor ‘CBigNum::CBigNum(long unsigned int)’:
bignum.h:90:35: error: ‘BN_init’ was not declared in this scope
     CBigNum(unsigned long n)    { BN_init(this); setulong(n); }
                                   ^~~~~~~
bignum.h:90:35: note: suggested alternative: ‘BN_print’
     CBigNum(unsigned long n)    { BN_init(this); setulong(n); }
                                   ^~~~~~~
                                   BN_print
bignum.h: In constructor ‘CBigNum::CBigNum(uint64)’:
bignum.h:91:35: error: ‘BN_init’ was not declared in this scope
     CBigNum(uint64 n)           { BN_init(this); setuint64(n); }
                                   ^~~~~~~
bignum.h:91:35: note: suggested alternative: ‘BN_print’
     CBigNum(uint64 n)           { BN_init(this); setuint64(n); }
                                   ^~~~~~~
                                   BN_print
bignum.h: In constructor ‘CBigNum::CBigNum(uint256)’:
bignum.h:92:35: error: ‘BN_init’ was not declared in this scope
     explicit CBigNum(uint256 n) { BN_init(this); setuint256(n); }
                                   ^~~~~~~
bignum.h:92:35: note: suggested alternative: ‘BN_print’
     explicit CBigNum(uint256 n) { BN_init(this); setuint256(n); }
                                   ^~~~~~~
                                   BN_print
bignum.h: In constructor ‘CBigNum::CBigNum(const std::vector<unsigned char>&)’:
bignum.h:96:9: error: ‘BN_init’ was not declared in this scope
         BN_init(this);
         ^~~~~~~

**Comment by Bushstar** [comment]
Compile with OpenSSL 1.0.1.

**Comment by red0bear** [comment]
Yes ... but you dont explain how to build from source correctly. Thats why you dont have a linux version ? 
Im trying to test your wallet .... but is bad under unix . Why dont try to use cmake ?

**Comment by Bushstar** [comment]
I'm in the process of porting Bitcoin 0.13 to Cannabiscoin, it should be available later today or tomorrow. The 0.13 branch currently available is not complete so please do not use it yet. 0.13 at least comes with its own dependencies folder containing all the required source to build the client. I'll post back here when the source is ready to compile.

Building Cannabiscoin is the same as building Bitcoin, the error above is quite a common one on newer version if Linux that no longer install OpenSSL 1.0.1 via the package management system. Wait until 0.13 is ready then compile using the depends folder.

**Comment by red0bear** [comment]
This is a good step to cannabis.

**Comment by Bushstar** [comment]
0.13 is now available with Linux binaries for 32bit and 64bit.

https://github.com/cannabiscoindev/cannabiscoin420/releases/tag/v0.13.0.0

**Comment by red0bear** [comment]
Can i test ? if i find something i will report !!!! :-))))))

**Comment by Bushstar** [comment]
Please do.
